(rule
 (targets rpath_flags.sexp)
 (deps ../../scripts/gen-rpath-sexp.sh)
 (action
  (with-stdout-to %{targets}
   (run sh %{deps}))))

(rule
 (targets static_link_flags.sexp)
 (deps ../../scripts/gen-static-link-sexp.sh)
 (action
  (with-stdout-to %{targets}
   (run sh %{deps} %{project_root}))))

(library
 (name arrow_c_api)
 (public_name arrow.c_api)
 (foreign_stubs
  (language c)
  (names arrow_c_api_stubs)
  (include_dirs %{project_root}/vendor/arrow-install/include))
 (foreign_stubs
  (language cxx)
  (names arrow_c_api)
  (flags :standard -fPIC -std=c++17)
  (include_dirs %{project_root}/vendor/arrow-install/include))
 (c_library_flags
  :standard
  (:include rpath_flags.sexp)
  (:include static_link_flags.sexp)
  -lstdc++)
 (libraries base bigarray core_kernel ctypes ctypes.foreign ctypes.stubs stdio)
 (inline_tests)
 (preprocess (pps ppx_expect ppx_sexp_conv)))

(install
 (package arrow)
 (section stublibs)
 (files
  (glob_files
   (../../vendor/arrow-install/lib/libarrow.a with_prefix .))
  (glob_files
   (../../vendor/arrow-install/lib/libarrow_bundled_dependencies.a with_prefix .))
  (glob_files
   (../../vendor/arrow-install/lib/libparquet.a with_prefix .))))

(rule
 (targets bindings.ml)
 (deps ../stubs/bindings.ml)
 (action (copy ../stubs/bindings.ml bindings.ml)))

(rule
 (targets arrow_c_api_stubs.c bindings_generated.ml)
 (deps (:gen ../stubs/gen.exe))
 (action (run %{gen})))
